version: '3'
services:
  resullme:
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - 8501:8501
    volumes:
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1